### ISSUE TITLE
Feedback does not work

### ISSUE THREAD

**Issue by TheLlamamarketer** [Contraversum/ContraBot#76]
After clicking on the button only the first question appears, then the bot does not continue.

**Comment by TheLlamamarketer** [comment]
I have found the root of the error, its in index.ts in the lines:
```
            const response = await sheets.spreadsheets.values.get({
                spreadsheetId: SHEET_ID,
                range: `${START_COLUMN}:${START_COLUMN}`  // search in the first column only
            });
```
No clue what's causing it, maybe something to do with the permissions of the bot. Maybe something has changed with google sheets? 
            
The accompanying error:
Error in Events.MessageCreate: Error: error:1E08010C:DECODER routines::unsupported
    at Sign.sign (node:internal/crypto/sig:131:29)
    at Object.sign (C:\Users\alexa\OneDrive\Documents\ContraBot\node_modules\jwa\index.js:152:45)
    at Object.jwsSign [as sign] (C:\Users\alexa\OneDrive\Documents\ContraBot\node_modules\jws\lib\sign-stream.js:32:24)
    at GoogleToken.requestToken (C:\Users\alexa\OneDrive\Documents\ContraBot\node_modules\gtoken\build\src\index.js:224:31)
    at GoogleToken.getTokenAsyncInner (C:\Users\alexa\OneDrive\Documents\ContraBot\node_modules\gtoken\build\src\index.js:158:21)
    at GoogleToken.getTokenAsync (C:\Users\alexa\OneDrive\Documents\ContraBot\node_modules\gtoken\build\src\index.js:137:55)
    at GoogleToken.getToken (C:\Users\alexa\OneDrive\Documents\ContraBot\node_modules\gtoken\build\src\index.js:96:21)
    at JWT.refreshTokenNoCache (C:\Users\alexa\OneDrive\Documents\ContraBot\node_modules\google-auth-library\build\src\auth\jwtclient.js:172:36)
    at JWT.refreshToken (C:\Users\alexa\OneDrive\Documents\ContraBot\node_modules\google-auth-library\build\src\auth\oauth2client.js:153:24)
    at JWT.getRequestMetadataAsync (C:\Users\alexa\OneDrive\Documents\ContraBot\node_modules\google-auth-library\build\src\auth\oauth2client.js:298:28) {
  library: 'DECODER routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_UNSUPPORTED'
}

**Comment by johan-t** [comment]
I think it would be better if I take this issue since, the issue is with the google API and I am the only one with access
